applications/persona/urls.py
# from django.contrib import admin
from django.urls import path  # , include
from . import views


def desde_apps2(self):
    print("wenass")


# Nombre para todo el conjunto de urls
app_name = 'empleados_app'

urlpatterns = [
    # path('persona/', desde_apps2),
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-empleados/', views.ListAllEmployees.as_view(), name='listar_empleados'),
    path('listar-empleados-admin/', views.ListAllEmployeesAdmin.as_view(), name='lista_empleados_admin'),
    path('listar-por-area/<id>', views.ListEmployeeByArea.as_view(), name='listar_por_area'),
    path('listar-por-trabajo/<job>', views.ListEmployeeByJob.as_view()),
    path('buscar-empleado/', views.ListEmployeeByKeyword.as_view()),
    path('listar-habilidades/', views.ListSkillsEmployee.as_view()),
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(), name='ver_empleado'),
    path('crear-empleado/', views.EmpleadoCreateView.as_view(), name='crear_empleado'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('actualizar-empleado/<pk>', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('eliminar-empleado/<pk>', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
]

empleados/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.home.urls')),
    # urls para multimedia
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from ckeditor.fields import RichTextField
from django.db import models

from applications.departamento.models import Departamento


class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades Empleado'

    def __str__(self):
        return f"{self.id} - {self.habilidad}"


# Create your models here.
class Persona(models.Model):
    """Modelo para tabla Persona"""
    JOB_TYPES = (
        ('0', 'Contador'),
        ('1', 'Administrador'),
        ('2', 'Economista'),
        ('3', 'Otro'),
    )

    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField('Nombre Completo', max_length=120, blank=True)
    job = models.CharField('Trabajo', max_length=1, choices=JOB_TYPES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', null=True, blank=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()

    # Con esto cambiamos el nombre que aparecera en el panel admin de django
    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'

    def __str__(self):
        # NOTA: Los PK Django los genera automaticamente si no lo queremos
        # modificar manualmente
        return f"{self.id} - {self.first_name} - {self.last_name}"

applications/persona/forms.py
from django import forms

from .models import Persona


class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Persona
        fields = ('first_name', 'last_name', 'job', 'departamento', 'avatar', 'habilidades',)
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple(),
        }

applications/persona/views.py
# from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DetailView, ListView,
                                  TemplateView, UpdateView, DeleteView)

from .models import Persona
from .forms import EmpleadoForm


class InicioView(TemplateView):
    """Vista que carga la pagina de inicio"""
    template_name = 'inicio.html'


# Requerimientos
# 1 - Listar todos los empleados de la empresa
class ListAllEmployees(ListView):
    template_name = 'persona/list_all_employees.html'
    paginate_by = 4
    ordering = 'id'
    context_object_name = 'lista_empleados'
    # model = Persona  # se usa cunado no se usa get_queryset
    # context_object_name = 'empleados'

    # Sirve para retornar data y filtrar
    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '')

        # icontains: sirve como si fuera %like%
        lista = Persona.objects.filter(
            full_name__icontains=palabra_clave
        )
        return lista


class ListAllEmployeesAdmin(ListView):
    template_name = 'persona/list_all_employees_admin.html'
    paginate_by = 10
    ordering = 'id'
    context_object_name = 'lista_empleados'
    model = Persona


# 2 - Listar todos los empleados de la empresa que pertenecen a una area
class ListEmployeeByArea(ListView):
    template_name = 'persona/list_by_area.html'
    model = Persona
    # queryset = Persona.objects.filter(departamento__name='Departamento de Ingenieria')
    context_object_name = 'empleados'

    def get_queryset(self):
        area = self.kwargs['id']
        lista = Persona.objects.filter(departamento__name=area)

        return lista


# 3 - Listar todos los empleados de la empresa por trabajo
class ListEmployeeByJob(ListView):
    template_name = 'persona/list_by_job.html'
    model = Persona

    # Se usa cuando queremos recibir algun parametro por URL del frontend
    def get_queryset(self):
        job = self.kwargs['job']
        lista = Persona.objects.filter(job=job)

        return lista


# 4 - Listar todos los empleados de la empresa por palabra clave
class ListEmployeeByKeyword(ListView):
    """Listado de empleados por palabra clave"""
    template_name = 'persona/list_by_keyword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get('keyword', '')

        lista = Persona.objects.filter(first_name=palabra_clave)
        return lista


# 5 - Listar habilidades de un empleado
class ListSkillsEmployee(ListView):
    template_name = 'persona/list_skills_employee.html'
    context_object_name = 'habilidades'
    model = Persona

    def get_queryset(self):
        empleado = Persona.objects.get(id=6)
        res = empleado.habilidades.all()
        return res


# Obligatoriamente se tiene que usar un PK para ver detalle de x registro
class EmpleadoDetailView(DetailView):
    model = Persona
    template_name = 'persona/details_employee.html'

    # Podemos enviar datos extras que no sean parte de un modelo
    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'
        return context


# SE USA EN SU MAYORIA SOLO PARA GENERAR PLANTILLAS HTML
class SuccessView(TemplateView):
    template_name = 'persona/success.html'


# INICIO SECCION DE CRUD
class EmpleadoCreateView(CreateView):
    model = Persona
    template_name = 'persona/add.html'

    # Forma 1: en caso se usa el modelo
    # fields = ['first_name', 'last_name', 'job', 'avatar', 'departamento', 'habilidades']
    # Forma 2: obtener todos los campos del modelo para el formulario
    # fields = ('__all__')

    # Forma 3: usando un formulario personalizado
    form_class = EmpleadoForm

    # Requiere una url para redireccionar, asignando un . la pagina se recarga
    # success_url = '.'
    # success_url = '/success'  # No es buena practica
    success_url = reverse_lazy('empleados_app:lista_empleados_admin')

    def form_valid(self, form):
        # Logica del proceso
        # Commit=False: No guarda en la BD solo en memoria para despues guardar
        empleado = form.save(commit=False)
        empleado.full_name = f'{empleado.first_name} {empleado.last_name}'
        empleado.save()

        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    model = Persona
    template_name = 'persona/update.html'
    fields = ['first_name', 'last_name', 'job', 'departamento', 'habilidades']
    success_url = reverse_lazy('empleados_app:lista_empleados_admin')

    def form_valid(self, form):
        # Logica del proceso
        # Commit=False: No guarda en la BD solo en memoria para despues guardar
        empleado = form.save(commit=False)
        empleado.full_name = f'{empleado.first_name} {empleado.last_name}'
        empleado.save()

        return super(EmpleadoUpdateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        """Se usa cuando se quiere validar data antes de que se ejecute form_valid,
        detecta los datos antes de validarlos y guardar
        """
        self.object = self.get_object()
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)


class EmpleadoDeleteView(DeleteView):
    model = Persona
    template_name = 'persona/delete.html'
    success_url = reverse_lazy('empleados_app:lista_empleados_admin')

    # # https://ccbv.co.uk/projects/Django/4.0/django.views.generic.edit/DeleteView/
    # def delete(self, request, *args, **kwargs):
    #     """
    #     Call the delete() method on the fetched object and then redirect to the
    #     success URL.
    #     """
    #     self.object = self.get_object()
    #     success_url = self.get_success_url()
    #     self.object.delete()
    #     # return HttpResponseRedirect(success_url)

templates/persona/add.html
{% extends 'base.html' %}
{% block title %}Crear Empleado{% endblock title%}
{% block contenido %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Crear Empleado</h1>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %} {{ form.as_p }}

            <button type="submit" class="button success">REGISTRAR</button>
        </form>

    </div>
</div>
{% endblock contenido %}

templates/persona/delete.html
{% extends 'base.html' %}
{% block title %}Actualizar Empleado{% endblock title%}
{% block contenido %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar Empleado {{ object.full_name }}</h1>

        <form class="cell" method="post">
            {% csrf_token %}
            <p>Confirme que desea eliminar el registro</p>
            <button type="submit" class="button alert">ELIMINAR</button>
        </form>

    </div>
</div>
{% endblock contenido %}

templates/persona/details_employee.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ persona.first_name }}{% endblock title%}
{% block contenido %}
{% include "includes/header.html" %}


<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <h1 class="cell">Detalles de empleado - {{ titulo }}</h1>

        <!-- {{ object }} -->
        <!-- Tambien se puede usar el nombre del modelo pero en minuscula -->
        <!-- {{ persona }} -->

        <div class="card cell large-4" style="width: 300px;">
            <div class="card-divider">
                {{ persona.first_name }} {{ persona.last_name }}
            </div>
            {% if persona.avatar %}
            <img src="{{ persona.avatar.url }}">
            {% else %}
            <img src="{% static 'img/avatar.png' %}">
            {% endif %}
            <div class="card-section">
                <p class="cell">{{ persona.first_name }}</p>
                <p class="cell">{{ persona.last_name }}</p>
                <p class="cell">{{ persona.departamento.short_name }}</p>
                <p><span class="label">HABILIDADES</span>
                    <ul class="vertical-menu">
                        {% for h in persona.habilidades.all %}
                        <li>{{ h.habilidad }}</li>
                        {% endfor %}
                    </ul>
                </p>
                <!-- <p class="cell">{{ persona.habilidades }}</p> -->
                <p class="cell">{{ persona.get_job_display }}</p>
                <p class="cell">{{ persona.hoja_vida }}</p>
            </div>
          </div>

    </div>
</div>
{% endblock contenido %}

templates/persona/list_all_employees.html
{% extends 'base.html' %}
{% block title %}Listado Empleados{% endblock title%}
{% block contenido %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Empleados</h1>
        <div class="cell grid-x grid-margin-x">
            <form method="GET" class="cell">
                {% csrf_token %}
                <div class="cell large-7">
                    <input
                        type="text"
                        name="kword"
                        id="kword"
                        placeholder="Buscar Empleado"
                    />
                </div>
                <div class="cell large-2">
                    <button type="submit" class="second button">Buscar</button>
                </div>
            </form>
        </div>

        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="25">ID</th>
                        <th width="auto">NOMBRES</th>
                        <th width="auto">APELLIDOS</th>
                        <th width="auto">DEPARTAMENTO</th>
                        <th width="80">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for empleado in lista_empleados %}
                    <tr>
                        <td>{{ empleado.id }}</td>
                        <td>{{ empleado.first_name}}</td>
                        <td>{{ empleado.last_name }}</td>
                        <td>{{ empleado.departamento }}</td>
                        <td>
                            <a
                                type="button"
                                class="warning button"
                                href="{% url 'empleados_app:ver_empleado' empleado.id %}"
                            >
                                Ver
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">
                    <!-- Validacion atras -->

                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a
                                class="enabled"
                                href="?page={{ page_obj.previous_page_number }}"
                                >Atras</a
                            >
                        </li>
                    {% else %}
                        <li class="pagination-previous disabled">
                            <a class="disabled">Atras</a>
                        </li>
                    {% endif %}

                    {% for pagina in paginator.page_range %}

                        {% if pagina == page_obj.number %}
                            <li class="current">
                                <span class="show-for-sr">You're on page</span> {{ pagina }}
                            </li>
                        {% else %}
                            <li>
                                <a href="?page={{pagina}}">{{ pagina }}</a>
                            </li>
                        {% endif %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}"
                                >Siguiente</a
                            >
                        </li>
                    {% else %}
                        <li class="pagination-next disabled">
                            <a class="disabled">Siguiente</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>

{% endblock contenido %}

templates/persona/list_all_employees_admin.html
{% extends 'base.html' %}
{% block title %}Listado Empleados{% endblock title%}
{% block contenido %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Empleados</h1>
                <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="25">ID</th>
                        <th width="auto">NOMBRES</th>
                        <th width="auto">APELLIDOS</th>
                        <th width="auto">DEPARTAMENTO</th>
                        <th width="80"></th>
                        <th width="80"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for empleado in lista_empleados %}
                    <tr>
                        <td>{{ empleado.id }}</td>
                        <td>{{ empleado.first_name}}</td>
                        <td>{{ empleado.last_name }}</td>
                        <td>{{ empleado.departamento }}</td>
                        <td>
                            <a
                                type="button"
                                class="success button"
                                href="{% url 'empleados_app:modificar_empleado' empleado.id %}"
                            >
                                Editar
                            </a>

                        </td>
                        <td>
                            <a
                                type="button"
                                class="alert button"
                                href="{% url 'empleados_app:eliminar_empleado' empleado.id %}"
                            >
                                Eliminar
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">
                    <!-- Validacion atras -->

                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a
                                class="enabled"
                                href="?page={{ page_obj.previous_page_number }}"
                                >Atras</a
                            >
                        </li>
                    {% else %}
                        <li class="pagination-previous disabled">
                            <a class="disabled">Atras</a>
                        </li>
                    {% endif %}

                    {% for pagina in paginator.page_range %}

                        {% if pagina == page_obj.number %}
                            <li class="current">
                                <span class="show-for-sr">You're on page</span> {{ pagina }}
                            </li>
                        {% else %}
                            <li>
                                <a href="?page={{pagina}}">{{ pagina }}</a>
                            </li>
                        {% endif %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}"
                                >Siguiente</a
                            >
                        </li>
                    {% else %}
                        <li class="pagination-next disabled">
                            <a class="disabled">Siguiente</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>

{% endblock contenido %}

templates/persona/list_by_area.html
{% extends 'base.html' %}

{% block title %}
Listado de Empleados por Departamento
{% endblock title %}

{% block contenido %}
{% include 'includes/header.html' %}

<!-- {{object_list}} -->

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Empleados</h1>
           <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="25">ID</th>
                        <th width="auto">NOMBRES</th>
                        <th width="auto">APELLIDOS</th>
                        <th width="auto">DEPARTAMENTO</th>
                        <th width="80">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for empleado in empleados %}
                    <tr>
                        <td>{{ empleado.id }}</td>
                        <td>{{ empleado.first_name}}</td>
                        <td>{{ empleado.last_name }}</td>
                        <td>{{ empleado.departamento }}</td>
                        <td>
                            <a
                                type="button"
                                class="warning button"
                                href="{% url 'empleados_app:ver_empleado' empleado.id %}"
                            >
                                Ver
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination text-center">
                    <!-- Validacion atras -->

                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a
                                class="enabled"
                                href="?page={{ page_obj.previous_page_number }}"
                                >Atras</a
                            >
                        </li>
                    {% else %}
                        <li class="pagination-previous disabled">
                            <a class="disabled">Atras</a>
                        </li>
                    {% endif %}

                    {% for pagina in paginator.page_range %}

                        {% if pagina == page_obj.number %}
                            <li class="current">
                                <span class="show-for-sr">You're on page</span> {{ pagina }}
                            </li>
                        {% else %}
                            <li>
                                <a href="?page={{pagina}}">{{ pagina }}</a>
                            </li>
                        {% endif %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}"
                                >Siguiente</a
                            >
                        </li>
                    {% else %}
                        <li class="pagination-next disabled">
                            <a class="disabled">Siguiente</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>

{% endblock contenido %}

templates/persona/list_by_job.html
<h1>Filtrado por Job</h1>

{{ object_list }}

<ul>
    {% for emp in object_list %}
    <li>{{ emp }}</li>
    {% endfor %}
</ul>

templates/persona/list_by_keyword.html
<h1>Buscar por palabra clave</h1>

<form method="get">
    {% csrf_token %}
    <input
        type="text"
        name="keyword"
        id="keyword"
        placeholder="Palabra clave"
    />
    <input type="submit" value="Buscar" />
</form>

{{ empleados }}

<ul>
    {% for empleado in empleados %}
    <li>{{ empleado.first_name }}</li>
    {% endfor %}
</ul>

templates/persona/list_skills_employee.html
<h1>Habilidades de empleado</h1>

<ul>
    {% for habilidad in habilidades %}
    <li>{{ habilidad }}</li>
    {% endfor %}
</ul>

templates/persona/success.html
<h1>EMPLEADO REGISTRADO</h1>

templates/persona/update.html
{% extends 'base.html' %}
{% block title %}Actualizar Empleado{% endblock title%}
{% block contenido %}
{% include "includes/header.html" %}


<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Actualizar datos de empleado</h1>

        <form method="post">
            {% csrf_token %} {{ form.as_p }}
            <button type="submit" class="button">ACTUALIZAR</button>
        </form>

    </div>
</div>
{% endblock contenido %}