applications/departamento/urls.py
# from django.contrib import admin
from django.urls import path  # , include  # re_path
from . import views


# Nombre para todo el conjunto de urls
app_name = 'departamento_app'

urlpatterns = [
    path('new-departamento/', views.NewDepartamento.as_view(), name='new_departamento'),
    path('lista-departamentos/', views.DepartamentoListView.as_view(), name='lista_departamento'),
]

applications/persona/urls.py
# from django.contrib import admin
from django.urls import path  # , include
from . import views


def desde_apps2(self):
    print("wenass")


# Nombre para todo el conjunto de urls
app_name = 'empleados_app'

urlpatterns = [
    # path('persona/', desde_apps2),
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-empleados/', views.ListAllEmployees.as_view(), name='listar_empleados'),
    path('listar-empleados-admin/', views.ListAllEmployeesAdmin.as_view(), name='lista_empleados_admin'),
    path('listar-por-area/<id>', views.ListEmployeeByArea.as_view(), name='listar_por_area'),
    path('listar-por-trabajo/<job>', views.ListEmployeeByJob.as_view()),
    path('buscar-empleado/', views.ListEmployeeByKeyword.as_view()),
    path('listar-habilidades/', views.ListSkillsEmployee.as_view()),
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(), name='ver_empleado'),
    path('crear-empleado/', views.EmpleadoCreateView.as_view(), name='crear_empleado'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('actualizar-empleado/<pk>', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('eliminar-empleado/<pk>', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
]

empleados/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.home.urls')),
    # urls para multimedia
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text"><a href="/">EMPLEADOS</a></li>
        <li>
            <a href="{% url 'empleados_app:listar_empleados' %}">Listar</a>
        </li>
        <li><a href="{% url 'departamento_app:lista_departamento' %}">Departamentos</a></li>
        <li><a href="{% url 'empleados_app:lista_empleados_admin' %}">Administrar</a></li>
        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
        <li><input type="search" placeholder="Buscar Empleado"></li>
        <li><a class="button" href="{% url 'empleados_app:crear_empleado' %}" >REGISTRAR NUEVO</a></li>
        </ul>
    </div>
</div>