applications/departamento/urls.py
# from django.contrib import admin
from django.urls import path  # , include  # re_path
from . import views


# Nombre para todo el conjunto de urls
app_name = 'departamento_app'

urlpatterns = [
    path('new-departamento/', views.NewDepartamento.as_view(), name='new_departamento'),
    path('lista-departamentos/', views.DepartamentoListView.as_view(), name='lista_departamento'),
]

applications/persona/urls.py
# from django.contrib import admin
from django.urls import path  # , include
from . import views


def desde_apps2(self):
    print("wenass")


# Nombre para todo el conjunto de urls
app_name = 'empleados_app'

urlpatterns = [
    # path('persona/', desde_apps2),
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-empleados/', views.ListAllEmployees.as_view(), name='listar_empleados'),
    path('listar-empleados-admin/', views.ListAllEmployeesAdmin.as_view(), name='lista_empleados_admin'),
    path('listar-por-area/<id>', views.ListEmployeeByArea.as_view(), name='listar_por_area'),
    path('listar-por-trabajo/<job>', views.ListEmployeeByJob.as_view()),
    path('buscar-empleado/', views.ListEmployeeByKeyword.as_view()),
    path('listar-habilidades/', views.ListSkillsEmployee.as_view()),
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(), name='ver_empleado'),
    path('crear-empleado/', views.EmpleadoCreateView.as_view(), name='crear_empleado'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('actualizar-empleado/<pk>', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('eliminar-empleado/<pk>', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
]

empleados/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.home.urls')),
    # urls para multimedia
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models


# Create your models here.
class Departamento(models.Model):
    # editable=False: No se puede editar en el admin
    name = models.CharField('Nombre', max_length=50, unique=True)
    # null=True si no hay valor se registra un null -> NULL
    short_name = models.CharField('Nombre Corto', max_length=25, blank=True, null=True)
    anulate = models.BooleanField('Anulado', default=False)

    # Con esto cambiamos el nombre que aparecera en el panel admin de django
    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'
        ordering = ['name']  # Descendente -> ['-name']
        unique_together = ('name', 'short_name')  # No permite que se registren combinaciones de datos repetidos

    def __str__(self):
        # NOTA: Los PK Django los genera automaticamente si no lo queremos
        # modificar manualmente
        return f"{self.id} - {self.name} - {self.short_name}"

applications/departamento/forms.py
from django import forms


class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    nombre_corto = forms.CharField(max_length=20)

applications/departamento/views.py
# from django.shortcuts import render
# from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import FormView

from applications.persona.models import Persona

from .forms import NewDepartamentoForm
from .models import Departamento


# vista para departamentos
class DepartamentoListView(ListView):
    model = Departamento
    template_name = 'departamento/departamento_list.html'
    context_object_name = 'departamentos'


# Create your views here.
class NewDepartamento(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'  # reverse_lazy('departamento:list_departamento')

    def form_valid(self, form):
        # form.save()

        depa = Departamento(
            name=form.cleaned_data['departamento'],
            short_name=form.cleaned_data['nombre_corto']
        )
        depa.save()

        nombre = form.cleaned_data['nombre']
        apellidos = form.cleaned_data['apellidos']
        Persona.objects.create(first_name=nombre, last_name=apellidos, job='1',
                               departamento=depa)

        return super().form_valid(form)

templates/departamento/departamento_list.html
{% extends 'base.html' %}
{% block title %}
Lista de departamentos
{% endblock title %}


{% block contenido %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos</h1>

            <div class="cell">
                <table class="hover unstriped">
                    <tbody>
                        {% for departamento in departamentos %}
                            <tr>
                                <td>{{ departamento.name }}</td>
                                <td>{{ departamento.short_name }}</td>
                                <td>
                                    <a
                                        type="button"
                                        class="warning button"
                                        href="{% url 'empleados_app:listar_por_area' departamento.name %}">
                                    >
                                        Ver Empleado
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock contenido %}

templates/departamento/new_departamento.html
{% extends 'base.html' %}
{% block title %}Actualizar Empleado{% endblock title%}
{% block contenido %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar nuevo departamento</h1>

        <form method="post">
            {% csrf_token %}
            <h3>Datos Empleado</h3>
            <p>{{ form.nombre }}</p>
            <p>{{ form.apellidos }}</p>

            <h3>Departamento</h3>
            <p>{{ form.departamento }}</p>
            <p>{{ form.nombre_corto }}</p>

            <!-- {{ form.as_p }} -->

            <button type="submit" class="button success">GUARDAR</button>
        </form>

    </div>
</div>
{% endblock contenido %}